runtime: php55
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: '/css/(.*)'
    application_readable: false
    static_files: "css/\\1"
    require_matching_file: false
    upload: 'css/.*'
  - url: '/font/(.*)'
    application_readable: false
    static_files: "font/\\1"
    require_matching_file: false
    upload: 'font/.*'
  - url: '/img/(.*)'
    application_readable: false
    static_files: "img/\\1"
    require_matching_file: false
    upload: 'img/.*'
  - url: '/js/(.*)'
    application_readable: false
    static_files: "js/\\1"
    require_matching_file: false
    upload: 'js/.*'
  - url: '/scripts/(.*)'
    application_readable: false
    static_files: "scripts/\\1"
    require_matching_file: false
    upload: 'scripts/.*'
  - url: '/videos/(.*)'
    application_readable: false
    static_files: "videos/\\1"
    require_matching_file: false
    upload: 'videos/.*'
  - url: "/favicon\\.ico"
    application_readable: false
    static_files: favicon.ico
    require_matching_file: false
    upload: "favicon\\.ico"
  - url: '.*'
    script: main.php
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  GA_TRACKING_ID: "UA-125589736-1"
